### PR TITLE
feat: added config options to change what code editor will be opened based on the files inside

### PR DESCRIPTION
**Pull request by CollinHemeltjen**
I have several projects that need to be opened in different code editors. Some I need in VSCode, some in Xcode and some in Android Studio. I tweaked the script a bit on my local machine to check the file extensions inside the folder and determine what editor to use based on that. 

My config code looks like this:
```
xed=.xcodeproj,.xcworkspace
studio=.gradle
code=*
```
In this case iOS projects get opened in Xcode, projects with a gradle file in them in Android Studio and all others in VSCode.
It only searches the top level to keep up performance and make sure some file nested deep in the folder doesn't accidentally match. Order of the list matters, once a match has been found the script will continue and won't check the other options.

I think the performance impact is minimal, but I am testing this on a M2 Macbook Pro so my observations are probably skewed.

### CODE REVIEW

**Comment by oe** [comment]
Great PR!
But storing config in a file is not a good idea, I'd like to take advantage of alfred's workflow configurations.

 I'll merge this first, then make some minor changes and do a final release. Stay tuned.

**Comment by oe** [comment]
I've made a few improvements:
1. support comments in configuration
2. support case-insensitive compare in `parseEditorCliConfig 
3. improve performance

You don't use a file to store config, sorry for my mistake.

I'm going on holiday, I'll make a final release when I'm back.

**Comment by CollinHemeltjen** [comment]
Awesome, improvements look good 🙌

**Comment by oe** [comment]
It has been released in v1.0.3, can be updated from the Afred Gallery.

**Pull request merged**
